/**
 * tailwind-config.js
 * Shared design tokens (colors, type, spacing, radius) pulled from the
 * office brand system. Edit ONLY this file to change colors/fonts site-wide.
 */
tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#f7be1d",
        "surface-tint": "#785a00",
        "on-primary-fixed-variant": "#5a4300",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary": "#785a00",
        "primary-container": "#eab308",
        "on-primary-container": "#604700",
        "primary-fixed": "#ffdf9a",
        "on-primary-fixed": "#251a00",
        "inverse-primary": "#f7be1d",
        "secondary": "#565e74",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "warning-yellow": "#FACC15",
        "outline": "#817660",
        "outline-variant": "#d3c5ac",
        "surface-dim": "#d8dadc",
        "background": "#f7f9fb",
        "slate-900": "#0F172A",
        "slate-800": "#1E293B",
        "slate-600": "#475569",
        "slate-400": "#94a3b8",
        "slate-200": "#E2E8F0",
        "surface-variant": "#e0e3e5",
        "surface-container-lowest": "#ffffff",
        "surface": "#f7f9fb",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "on-surface-variant": "#4f4633",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "success-teal": "#0D9488",
        "success-container": "#ccfbf1",
        "error-crimson": "#991B1B",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
      },
      borderRadius: { DEFAULT: "0.125rem", lg: "0.25rem", xl: "0.5rem", full: "0.75rem" },
      spacing: { "margin-desktop": "40px", gutter: "24px", "container-max": "1440px", "margin-mobile": "16px", unit: "4px" },
      fontFamily: {
        "body-md": ["Inter"], "label-md": ["JetBrains Mono"], "mono-sm": ["JetBrains Mono"],
        "body-lg": ["Inter"], "headline-md": ["Hanken Grotesk"], "headline-lg-mobile": ["Hanken Grotesk"],
        "body-sm": ["Inter"], "display-lg": ["Hanken Grotesk"], "headline-lg": ["Hanken Grotesk"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
};
